project:
  type: website

website:
  title: "Pulse"
  navbar: false
  # page-footer: 
  #   left: "Copyright 2021, Norah Jones" 
  #   right: 
  #     - icon: github
  #       href: https://github.com/
  #     - icon: twitter 
  #       href: https://twitter.com/ 

format:
  html:
    theme: cosmo
    css: styles.css
    smooth-scroll: false



